### ISSUE TITLE
Fluent Icon Style Guidelines

### ISSUE THREAD

**Issue by ehnguyen09** [microsoft/fluentui-system-icons#107]
I'm trying to design a set of icons that's meant to be integrated with fluent icons. I was wondering if you could direct me to a style guideline for designing Fluent icons.

@jasoncuster @spencer-nelson @thewoodpecker

**Comment by jasoncuster** [comment]
Hey @ehnguyen09 - these are now included in the figma file. [Take a look](https://www.figma.com/community/file/836835755999342788/Microsoft-Fluent-System-Icons) and let use know if there's any details left out.
