### ISSUE TITLE
The Figma for Fluent UI Icons is out of date

### ISSUE THREAD

**Issue by mdtauk** [microsoft/fluentui-system-icons#111]
The changelog for the Figma file, has not noted any updates since the 5th August.

https://www.figma.com/community/file/836835755999342788

**Comment by jasoncuster** [comment]
Sorry @mdtauk - it's been updated once since your comment, but I'm going to be pushing an update this week with all new icons, a new format, variants, and guidelines (which I promised you a loooong time ago...haha). I'll update when it's up.

**Comment by mdtauk** [comment]
Is there a way to roll up the figma file to update as the repo is updated?

I guess I kinda assumed the icons were being designed in Figma directly, then exported to SVG and PDF - but I guess its more likely to be through Adobe Illustrator which supports PDF natively, whereas Figma doesn't.

**Comment by jasoncuster** [comment]
They are being created in Figma, but right now we have an internal library as the source of truth, and we have to transfer those over to the community file, as ours contains internal links, docs, and brand icons. It's a good idea though to have it as one file to keep things easier to update - I'll have a think on that.

**Comment by jasoncuster** [comment]
No more difficulty updating that file. We'll update with our internal sprints. It's was updated today, take a look! And as always, thank you for your feedback @mdtauk - you're a great contributor.
