### ISSUE TITLE
Add 5G icon

### ISSUE THREAD

**Issue by alexmcroberts** [microsoft/fluentui-system-icons#113]
Scrolling through the full list of issues I noticed the 3G and 4G cell network icons. While it's still a relatively new technology – it would be useful to add a 5G one too

**Comment by tanmaya0102** [comment]
Please check my new pull request, I added 5G icon . I designed it myself using Adobe XD

**Comment by jasoncuster** [comment]
@alexmcroberts - we've added one! @tanmaya0102 - As we were working on updating type we had the chance to get this one in. Sorry about the duplicate effort, but thank you for your work.
