### ISSUE TITLE
Readme description is meaningless

### ISSUE THREAD

**Issue by idontusenumbers** [microsoft/fluentui-system-icons#114]
> Fluent UI System Icons are a collection of familiar, friendly and modern icons from Microsoft.

What does it mean to be familiar, friendly, or modern?

Proposal:
`Fluent UI System Icons is a collection of icons from Microsoft intended to produce a consistent user experience throughout the platform.`

**Comment by spencer-nelson** [comment]
Thank you for your comment. We will bring this up with the greater Fluent UI team to make sure we align with their wording and re-open this as necessary.
