### ISSUE TITLE
Icon request: Fire/Flame icon

### ISSUE THREAD

**Issue by cervonwong** [microsoft/fluentui-system-icons#125]
Possible usages:

- Heat in weather apps
- Streak in gamification apps (e.g. education)
- Hot deals / Hot (popular) items
- Something burning

**Comment by cervonwong** [comment]
![image](https://user-images.githubusercontent.com/44718681/126162778-db05963e-1132-4bd1-ad26-c7fe8e5a5e77.png)
I noticed in a post [by @microsoft.design](https://www.instagram.com/p/CRRWZCmH1Hr/) that I assume features fluent system icons and has a fire icon. Has the fire icon been included in this icon pack? Thanks!

**Comment by jasoncuster** [comment]
This icon has been added to the list for tomorrows merge.

**Comment by jasoncuster** [comment]
These icons have been added.

**Comment by luohao123** [comment]
@jasoncuster Hello, I search and use in flutter, the fire / hot/ flame can not search this icon.....
