### ISSUE TITLE
Rename Mail Unsubscribe to Mail Off?

### ISSUE THREAD

**Issue by cervonwong** [microsoft/fluentui-system-icons#136]
It has a slash through the standard Mail icon. And other icons use the "Off" suffix to represent this.

**Comment by jasoncuster** [comment]
@cervonwong - we're in the process of updating the library, which should come tomorrow or Wed, and this will be part of that update. Thank you again for the suggestion.

**Comment by jasoncuster** [comment]
This has been updated! Thank you for the suggestion!
