### ISSUE TITLE
Play icon is optically misaligned

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/fluentui-system-icons#137]
While play icon is technically centered within its canvas, it does appear optically misaligned because of its shape:
![723F41F9-8224-46F4-805E-2A750600D5AE](https://user-images.githubusercontent.com/8152849/100430381-0232a300-3097-11eb-81ee-8b1d0e8189f6.jpeg)

While this can be easily worked around I feel like this should be fixed in the resources itself, even if it’s kind of a breaking change.

**Comment by jasoncuster** [comment]
Agreed - thanks @FrayxRulez for pointing it out.

**Comment by jasoncuster** [comment]
@FrayxRulez - the play icons have been updated. Take a look and let us know if it works better for your use. Thank you!

**Comment by FrayxRulez** [comment]
Perfect, thanks!
