### ISSUE TITLE
Some media controls are missing

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/fluentui-system-icons#138]
This is the list of currently supported media controls icons:
- Play
- Pause
- Fast forward
- Rewind
- Next track
- Previous track
- Repeat on
- Repeat off
- Volume levels

Still, some of them are missing:
- Repeat 1
- Shuffle on
- Shuffle off

Would be great if you could include them in the pack!

**Comment by NGame1** [comment]
Since the 3rd of December, it is not added yet.

**Comment by NGame1** [comment]
@jasoncuster After about 2 years, is there any hope to add shuffle and "repeat one" icons?

**Comment by jasoncuster** [comment]
Apologies gang - time keeps moving on, but we've added Arrow Repeat 1, Arrow Shuffle & Shuffle Off to the merge list for tomorrow.

**Comment by NGame1** [comment]
That's nice. Finally.

**Comment by jasoncuster** [comment]
These icons have been added.
