### ISSUE TITLE
Invalid dimensions in a few icons

### ISSUE THREAD

**Issue by cyberalien** [microsoft/fluentui-system-icons#147]
Several SVGs have incorrect dimensions:

ic_fluent_more_24_regular.svg: 25 x 24
ic_fluent_more_24_filled.svg: 25 x 24
ic_fluent_more_28_regular.svg: 29 x 28
ic_fluent_more_48_filled.svg: 49 x 48
ic_fluent_more_48_regular.svg: 49 x 48
ic_fluent_scale_fit_16_filled.svg: 17 x 16
ic_fluent_scale_fit_16_regular.svg: 17 x 16
ic_fluent_scale_fit_20_filled.svg: 21 x 20
ic_fluent_scale_fit_24_filled.svg: 25 x 24
ic_fluent_scale_fit_20_regular.svg: 21 x 20
ic_fluent_text_number_format_24_regular.svg: 20 x 20
ic_fluent_weather_hail_day_24_filled.svg: 48 x 48
ic_fluent_weather_hail_night_24_filled.svg: 48 x 48
ic_fluent_weather_thunderstorm_24_filled.svg: 48 x 48

Would it make sense to fix them and make a pull request? Or are SVGs generated, so fixing them in pull request would be pointless?

**Comment by spencer-nelson** [comment]
Thanks for bringing these up. They should all be corrected in a new PR this week. Note that More has been renamed to More Horizontal
