### ISSUE TITLE
Errors in ic_fluent_cloud_download_32

### ISSUE THREAD

**Issue by cyberalien** [microsoft/fluentui-system-icons#148]
Both regular and filled SVGs for ic_fluent_cloud_download_32 have errors. This is what they look like:
![ic_fluent_cloud_download_32](https://user-images.githubusercontent.com/822287/103463953-e034dc00-4d38-11eb-984e-90fbcdf5e8f3.png)

Links to SVG:

https://github.com/microsoft/fluentui-system-icons/blob/master/assets/Cloud%20Download/SVG/ic_fluent_cloud_download_32_regular.svg

https://github.com/microsoft/fluentui-system-icons/blob/master/assets/Cloud%20Download/SVG/ic_fluent_cloud_download_32_filled.svg

PDF files for those icons do not have errors.

**Comment by jasoncuster** [comment]
This has been updated in the recent merge. Thanks for the feedback and for using the icons!
