### ISSUE TITLE
Cellular 3G (Regular) isn't consistent with Cellular 4G (Regular)

### ISSUE THREAD

**Issue by ItzLevvie** [microsoft/fluentui-system-icons#149]
I have noticed that the signal bar (the 5th one) at the very far right on the Cellular 3G (Regular) icon is slightly different than the one that the Cellular 4G (Regular) icon has.

Cellular 3G (Regular): 
![3g](https://user-images.githubusercontent.com/11600822/103541322-2ef68900-4e93-11eb-902a-dc570825fd39.png)

Cellular 4G (Regular): 
![4g](https://user-images.githubusercontent.com/11600822/103541351-36b62d80-4e93-11eb-9ba8-6e1f76c82ffd.png)

Opening them side-by-side on a browser, say like Microsoft Edge Canary, you can see the differences easily.

Is this intentional?

**Comment by jasoncuster** [comment]
Hey @ItzLevvie - thanks for the eagle eyes! It seems the 4G bar (regular) was for some reason a bit thinner. I've added it to the list of updates coming next push.

**Comment by jasoncuster** [comment]
Hey @ItzLevvie - this issue has been updated in our recent push. Thanks for the detailed look!
