### ISSUE TITLE
Windows App Support

### ISSUE THREAD

**Issue by TheJoeFin** [microsoft/fluentui-system-icons#15]
I am a Windows app developer and would like a Nuget package with all of these icons included.

**Comment by duke7553** [comment]
@spencer-nelson Any update on this?

**Comment by spencer-nelson** [comment]
Hi, we are looking at the roadmap with our partners to evaluate bandwidth to take this on. We will update when we have an estimate for delivery

**Comment by dpaulino** [comment]
I'm wondering this as well. Windows App support would be my number 1 request

**Comment by mossyblog** [comment]
Ummmm.... partners....

Tell me you're not outsourcing the UI for fluent UI to a design agency....

**Comment by samiq** [comment]
in all fairness it says here that this is for mobile platforms :) but would be good to be more embracing specially if they were to made to work easier with Xamarin Forms, Windows apps, Flutter and React Native

**Comment by mdtauk** [comment]
> 
> 
> Hi, we are looking at the roadmap with our partners to evaluate bandwidth to take this on. We will update when we have an estimate for delivery

Slightly worrying that Windows was not on the agenda from day 1.  These icons are being touted as an evolution of MDL2 iconography, and these originated from Windows and Windows Phone.

It certainly adds more fuel to the opinion that Windows is somewhat of an after-thought these days within Microsoft.

**Comment by spencer-nelson** [comment]
This effort started as a mobile-first icon redesign for the mobile products within the company and we wanted to make it available to the public as soon as we could do so. We understand your frustration and apologize for not having a better Windows solution already available. I also apologize and should have been more clear that we are working closely with our partners in the Windows team and will have something to talk about soon.

That being said, we encourage community engagement so if you would like to make a proposal for a Windows app development solution and start the work there, please feel welcome to do so. We would love to work with you on that.

**Comment by yoshiask** [comment]
I made this library [here](https://github.com/yoshiask/FluentSystemIconsUWP) for anyone who really wants to use these new icons. You should be able to just reference the `Microsoft.Design.Fluent` package in your app project. It's still a bit rough around the edges, but it does work.

**Comment by yoshiask** [comment]
^ This library is now available via NuGet: https://www.nuget.org/packages/Fluent.Icons

**Comment by 1217950746** [comment]
I created a WPF version
 https://github.com/1217950746/Fluent-System-Icons

**Comment by emiliano84** [comment]
Still no support for their own OS

**Comment by dpaulino** [comment]
Any updates regarding official support for Windows apps, particularly UWP/WinUI?

**Comment by yoshiask** [comment]
@spencer-nelson I'm looking into opening a PR to add UWP support, how should I go about doing that? The contributing guidelines don't say how to add support for a new platform, and the solutions for the existing platforms all appear to be very different from each other. My generator and base library is [here](https://github.com/yoshiask/FluentSystemIconsUWP). Here's a brief overview of the structure of the solution:

### Fluent.Icons
A .NET Standard 2.0 project that is what gets compiled and published as a package. The most important part is that `FluentSymbolIcon` is a partial class, split over two files: `FluentSymbolIcon.cs` (which is static) and `FluentSymbolIcon.g.cs` (which is what the generator project outputs). `FluentSymbolIcon.cs` contains the logic that directly interfaces with the generated content.

### FluentIconGenerator
.NET Framework 4.7.2 (it can be changed to .NET Core if necessary) console application that generates `FluentSymbolIcon.g.cs`, which contains an enum for all the included symbols, and a dictionary where the key is that enum and the value is a string representing the geometry of that icon (it pulls the data from every path in the SVGs and concatenates them). I tried using Source Generators and then Roslyn, but just a simple StringBuilder with a template works well enough.
This console program makes a few assumptions about where the library project and cloned repo are if not specified in the CLI arguments. It assumes that the provided icon directory (the input) is the `assets` folder of `microsoft/fluentui-system-icons`.

### FluentSystemTestApp
This is just a basic UWP app that lists all of the available icons and their names (as represented by the enums), along with a few common scenarios. This project is not necessary to the library itself; it's just a sample app.

**Comment by dpaulino** [comment]
@yoshiask perfect timing with your comment. I spoke with Spencer internally and I'd like to help spearhead windows support on his team's behalf. My first goal is to take a look at the solution you created. Give me a couple days to review your code and understand what you did.

**Comment by emiliano84** [comment]
Glad to see some love from the community, sad to see not much love directly from Microsoft

**Comment by dpaulino** [comment]
@yoshiask I've been reviewing the UX for consuming the package you created, and it's so far a nice experience! One improvement we'll need is the ability to use different icon sizes. In the iOS example, you can see here that the icon name includes its size and whether or not it's filled:
![image](https://user-images.githubusercontent.com/7649589/93731747-34012800-fb83-11ea-9770-3b6b461144e8.png)

Meanwhile, your package right now doesn't seem to support the different font sizes yet.
![image](https://user-images.githubusercontent.com/7649589/93731739-2fd50a80-fb83-11ea-8848-5fa1e34a275a.png)

Would you be able to add support for different font sizes?

**Comment by yoshiask** [comment]
@dpaulino Yes, it should be pretty easy to do. Might even be available by the next version!

**Comment by yoshiask** [comment]
I forgot to share here, the last two releases of [my library](https://www.nuget.org/packages/Fluent.Icons/) have support for all icon sizes, not just 24px.

**Comment by FrayxRulez** [comment]
The major obstacle that I can see here is the fact that UWP controls are designed to use 16px icons without plating, while here the vast majority are plated 24/20px icons.
I did some checks and I can see that 2145 out of 3346 of the 20px icons have their height that's 16px or less, so they could fit in UWP.

**Comment by FrayxRulez** [comment]
I made a small experiment to remove the plate to 24px icons to make them 20, and 20px icons to make them 16.
This is the result:
[FluentSystemIcons-Regular.zip](https://github.com/microsoft/fluentui-system-icons/files/5579925/FluentSystemIcons-Regular.zip)

**Comment by yoshiask** [comment]
> The major obstacle that I can see here is the fact that UWP controls are designed to use 16px icons without plating, while here the vast majority are plated 24/20px icons.

There appears to be good news on this front. Tooling is being developed to generate (?) the other scales from only the 20px glyph. On top of that, the official guidelines now state that 20px is the scale to design for first (at least that's what it sounded like to me).

See #

**Comment by HppZ** [comment]
no official support for UWP?

**Comment by mdtauk** [comment]
> no official support for UWP?

They do generate Fonts which you can use in a UWP app.  And UWP is adding support for SVG Icons.

Windows will eventually adopt this set of icons, possibly with the "Sun Valley" refresh coming in October (21H2)

**Comment by ismaelestalayo** [comment]
Are we allowed to include this font's TTF file in our apps so no matter what Windows 10 version the user is on, they all get the same consistent iconography?

**Comment by spencer-nelson** [comment]
This repo is under the MIT license, so you can do anything with it that falls under the constraints of that license.

**Comment by JanRajnoha** [comment]
It will be almost year since this issue was created. Will be official library? Will it support WinUI3?

**Comment by yoshiask** [comment]
IIRC, the next Windows feature update will include a new version of Segoe MDL2 Assets that uses these Fluent icons. You should be able to use them with `SymbolIcon` and `FontIcon` just as you do the older icons now.

**Comment by ghost1372** [comment]
> It will be almost year since this issue was created. Will be official library? Will it support WinUI3?

i created a nuget package that support winui 3
https://www.nuget.org/packages/WinUI3.Fluent.Icons

**Comment by TheJoeFin** [comment]
It has been 20 months since this issue was created. Does the team have any update with regards to support for Windows apps?

**Comment by HppZ** [comment]
> It has been 20 months since this issue was created. Does the team have any update with regards to support for Windows apps?

they don't.

**Comment by TheJoeFin** [comment]
I stumbled upon the answer to this issue. Windows 11 ships with a font called "Segoe Fluent Icons" installed. Also, I discovered when building an app with the Windows App SDK the Symbol Icon uses fluent icons.

From my understanding Fluent Icons are currently on Windows 11 and new apps built with the Windows App SDK. Currently no word on support for Windows 10.

I am going to close this issue. Someone else could make a new issue specific to track Windows 10 support if they like.

**Comment by JuandreG** [comment]
The https://www.nuget.org/packages/WinUI3.Fluent.Icons package does not seem to support x64

**Comment by AnalogFeelings** [comment]
2023, still no support for their own OS and UI library...

**Comment by Natriss** [comment]
@TheJoeFin Can you please reopen this issue?
This in not completed yet.
Windows 11 does indeed have Segoe Fluent Icons font but those are not the same as the ones that are available here.

You will never find all of these icons here in the Segoe Fluent Icons font.
Since both are Fluent icons and follows the same design. Why can't all of these icons be included in Windows 11 itself?

This would increase the needed space but as a developer it would be highly appreciated that we have access to all of the latest icons.

**Comment by TheJoeFin** [comment]
@spencer-nelson does it make sense for this issue to be reopened?

**Comment by Natriss** [comment]
Not anymore.
I made a new issue for it.

Is there a nuget package available of it that is also fully updated?

**Comment by yoshiask** [comment]
I haven't used it myself, but there is https://github.com/davidxuang/FluentIcons, which supports UWP, WinUI, and a few other UI frameworks as well.
