### ISSUE TITLE
Inconsistency with Regular/Filled icons that have a pen

### ISSUE THREAD

**Issue by TaigaYamada** [microsoft/fluentui-system-icons#155]
Hi. This is the first time posting an issue for me, and I am very new to open source communities, so please correct me if there are any errors.
I love the fluent system icons, so I thought I should take this opportunity to join in.

**Now for the issue itself:**

Some of the icons in this set have a smaller, secondary icon that modifies the meaning of the original icon. One such modification is the pen.

However, whether or not that pen is filled or outlined seems to be inconsistent.

This can be found in icons such as:

### Those with outlined pen for regular styles (I believe this is the intended design):
- Draw Shape (Regular)
- Draw Text (Regular)
- Image Edit (Regular)
- Link Edit (Regular)
- Speaker Edit (Regular)
- Status (Regular)
- Text Edit Style (Regular)
- Whiteboard (Regular)

### Those with filled pen, even for regular styles:
- Camera Edit (Regular)
- Comment Edit (Regular)
- Document Edit (Regular)
- People Edit (Regular)
- Save Edit (Regular)
- Star Edit (Regular)
- Table Edit (Regular)

### Those with outlined pen for filled styles:
- Image Edit (Filled)

I believe the pen should be outlined for all icons in the regular style, while pen should be filled in all icons in the filled style.

I tried to look for all instances of the problem, but there may be some that I missed.

**Comment by cervonwong** [comment]
Great spot, but maybe we can exclude `Draw Shape (Regular)` and `Draw Text (Regular)` from the comparison. 

It looks like a different kind of pen is being used.
Also, `Shape (Regular)` does not exist for `Draw Shape (Regular)` and `Text (Regular)` looks different from `Draw Text (Regular)`, so I don't think these two icons are part of the 'Edit' icons. 

Also, is it fair to classify the 'Edit' pen as a modifier as per the guidelines in the Figma file? If so then would the pen be filled?

**Comment by mdtauk** [comment]
I think it may be worth considering setting out a "kit of parts" so things like Pens for edit Icons, or the Modifiers are listed at all the icon sizes - and when you are creating custom icons, or new Icons to contribute, there will be consistency.

**Comment by TaigaYamada** [comment]
After thorough reading of the figma guidelines, it seems that all pens should be filled, if they are considered to be "modifiers".

Guidelines Foundation 6:
> We use solid modifiers to make them as legible as possible.

Although, it might be worth considering filling other small pen icons that aren't considered as "modifiers" regardless, because they face the same challenge of ensuring legibility in small sizes.

**Comment by jasoncuster** [comment]
Hey gang! Thanks @TaigaYamada for the note - and yeah, there are some inconsistencies with the pen. Some of those were created early on before we put together template pieces for teams to use and they need to be updated. And you're right, they should all be filled to help with readability. We'll add that to the list - though we have a few teams that dropped big lists for us we'll need to crank out first...haha. So it may be another few weeks before we push.

Also note, when time allows we'll add the template pieces for in the community file to keep consistency as we expand the library.

**Comment by jasoncuster** [comment]
Hey @TaigaYamada - the adjustments have been made in this most recent push. Thank you again for close look!

**Comment by TaigaYamada** [comment]
Image Edit (Regular), Image Edit (Filled) seems to have an outlined pen

**Comment by TaigaYamada** [comment]
This is now fixed as well
