### ISSUE TITLE
Inconsistency with stroke cut outs in icons with settings modifier

### ISSUE THREAD

**Issue by TaigaYamada** [microsoft/fluentui-system-icons#156]
As per Figma guideline Creation - Strokes 7, point 1:

> The shape should be 1px size (no matter the icon size) from the edge of the glyph

Stroke width rule is different for modifiers compared to normal icons, but the cut out rules of the strokes seems to be shared.

Then, the icons with gear modifier have inconsistent stroke cut outs compared to others.

Instead of the cut out starting from the "edge of the glyph", cut out seems to be based on a circle that is drawn around the gear.

This can be observed in following icons:
- Calendar Settings (Regular)
- Calendar Settings (Filled)
- Content Settings (Regular)
- Content Settings (Filled)
- Dual Screen Settings (Regular)
- Dual Screen Settings (Filled)
- Edit Settings (Regular)
- Edit Settings (Filled)
- Mic Settings (Regular)
- Mic Settings (Filled)
- People Settings (Regular)
- People Settings (Filled)
- Speaker Settings (Regular)
- Speaker Settings (Filled)
- Star Settings (Regular)
- Star Settings (Filled)
- Table Settings (Regular)
- Table Settings (Filled)
- Text Grammar Settings (Regular)
- Text Grammar Settings (Filled)

I have tried to find all instances of the problem, but I may have missed some.

Other non-circle shaped modifiers follow the guideline and start their cut outs from the edge of the glyph.
For example:
- Text Grammar Settings (Regular)
- People Search (Regular)
- People Swap (Regular)
- Person Call (Regular)

**Comment by jasoncuster** [comment]
Thanks for the note @TaigaYamada. This one is actually intended that way, as it helps with readability in between the slots for the gears. I agree it's inconsistent enough to set my teeth on edge, but we did some variations and it did help with readability.

**Comment by TaigaYamada** [comment]
I see! The gear modifier indeed has more complex shape than others, so it makes sense why the cut out is simplified. 

Maybe it might be worth updating the guidelines to mention that cut outs for complex shapes may start from simplified geometry instead of the edge of the glyph to improve legibility.

**Comment by TaigaYamada** [comment]
Now with the addition of "Creation tools" section on the guideline and the indication of the cutout geometry, it is abundantly clear that the circular cutout of the settings modifier is intentional simplification. So this issue can be closed now.
