### ISSUE TITLE
Port icons

### ISSUE THREAD

**Issue by TaigaYamada** [microsoft/fluentui-system-icons#174]
This icon pack already has a Serial Port icon, so I thought it would be great to have icons for other port types as well.

I am sadly not too familiar with Figma, so I am submitting my designs in `.svg` files.

**Icons I am submitting for review:**
- Hdmi
- Usb C
- Usb A
- Micro Usb

All icons are in 24 px size and in both Regular and Filled style.

**Design notes:**
- All applicable corners are rounded with 2px radius, because larger radius made the port shape harder to identify
- Smaller ports have smaller icons, but they are not fully proportionally scaled to improve legibility

**Here are the files:**
[Port icons.zip](https://github.com/microsoft/fluentui-system-icons/files/5899877/Port.icons.zip)

**Preview (with Serial Port icon for comparison):**
![Port icons_Icon preview](https://user-images.githubusercontent.com/77144664/106386945-c9a6a100-641a-11eb-9b96-662bbb82ea64.png)

**Comment by Jay-o-Way** [comment]
Pardon me, but especially the filled versions do not look (enough) like the actual plugs. The open USB-C plug is _kinda_ recognisable, but the filled one is just a well rounded dash. Can't use the male/female version as an argument here either.

**Comment by TaigaYamada** [comment]
Yeah, I do agree. It may be better to forego filling in for usb-c and micro-usb, instead using thicker strokes

**Comment by jasoncuster** [comment]
Hi @TaigaYamada - we added these icons to the set on Friday - (all under Port naming). Note that as we only rename on a quarterly timing now to not disrupt engineering teams - so Serial Port is still the outlier, but we'll update in a few weeks.

Thank you again for digging into the details and filing some of the holes in the set. You are great!

**Comment by TaigaYamada** [comment]
It's great pleasure to be able to contribute to this great project! I'm excited to see where the development goes.
