### ISSUE TITLE
Remove or add some warning with old name icon

### ISSUE THREAD

**Issue by tsuruobiz** [microsoft/fluentui-system-icons#187]
I use the great icons. I know some commit changes icon name. for example, https://github.com/microsoft/fluentui-system-icons/commit/1955eba88e4865a90a17dad137905b1737cfef1d. 
But still old name icon **exists  in `fluent_icon.dart` file**,  and  even **don't show me some linter warning.**  So, I cannot recognize either NAME CHANGED or NOT.

#### Example
[the commit](https://github.com/microsoft/fluentui-system-icons/commit/1955eba88e4865a90a17dad137905b1737cfef1d) changes  `text_bullet_list_24_regular` to `text_bullet_list_ltr_24_regular`

![108006272-5a49c780-703e-11eb-94f2-e0947eb7edfa](https://user-images.githubusercontent.com/59546923/108967440-e0ab7c80-76c2-11eb-8603-7d94d6064625.png)

`text_bullet_list_24_regular` is old name icon, but still exists `text_bullet_list_24_regular` in `fluent_icon.dart`.

![Simulator Screen Shot - iPhone 12 Pro - 2021-02-24 at 11 28 12のコピー](https://user-images.githubusercontent.com/59546923/108966891-2156c600-76c2-11eb-95aa-2c564775c705.png)

I think old name should be removed or show developer some linter warning. 

```
fluentui_system_icons:version: "1.1.98"
```

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

• No issues found!
```

Thanks.

**Comment by tsuruobiz** [comment]
@spencer-nelson 

Nice PR https://github.com/microsoft/fluentui-system-icons/pull/212, thanks. 

But in Flutter, you can still reference `dead icons` that were deprecated or renamed via `fluent_icons.dart` file. 
So, dead codepoint in `fluent_icons.dart` should be also removed, I think.
https://github.com/microsoft/fluentui-system-icons/blob/master/flutter/lib/src/fluent_icons.dart

**Comment by aakash1313** [comment]
Hey @tsuruobiz , the following PR was merged yesterday and the updated fluent_icons.dart would be present in the upcoming release. Please let us if you still see issues in the latest release . Thanks

**Comment by tsuruobiz** [comment]
@aakash1313 

Thanks for your quick response.

> updated fluent_icons.dart would be present in the upcoming release.

Okay, I see thet you work in progress the issue.
I'm looking forward to upcoming release! Thanks.

**Comment by tsuruobiz** [comment]
@aakash1313 

Today, my pacakges update to latest version `1.1.119`.
And then, my dart code detects compile error expectedly when I reference removed or renamed icon! 

![image](https://user-images.githubusercontent.com/59546923/115834709-7c056780-a450-11eb-83de-6476fabb0aa8.png)

So, close the issue. Thanks🙌
