### ISSUE TITLE
Fluent should have an online library catalog for icons

### ISSUE THREAD

**Issue by prysmanta** [microsoft/fluentui-system-icons#194]
Fluent should have an online library catalog for icons much like https://material.io/resources/icons to guide people on how to use fluent in their apps for both desktop and mobile as I have noticed the use of them in the [Microsoft Teams Electron App](https://teams.microsoft.com).

![image](https://user-images.githubusercontent.com/65317109/109375155-71699e80-78f5-11eb-9b89-a41da7638a6b.png)

**Comment by jeremy-coleman** [comment]
have fun
https://uifabricicons.azurewebsites.net/

**Comment by mdtauk** [comment]
> have fun
> https://uifabricicons.azurewebsites.net/

Those are the older MDL2 icons, and not the newer **Fluent UI System Icons**

**Comment by danielweck** [comment]
Indeed, it would be nice to be able to browse the huge icon collection easily, with textual search, preview in different sizes / stroke width, light/dark mode support, custom CSS color + fill, etc.

A few examples come to mind:

* Feather icons https://feathericons.com (even the stroke width can be adjusted)
* Heroicons (TailwindCSS) https://heroicons.com
* Bootstrap icons (Twitter) https://icons.getbootstrap.com
* Octicons (GitHub) https://octicons-primer.vercel.app/octicons
* Ionic icons https://ionicons.com
* Material Design icons (Google) https://material.io/resources/icons and https://materialdesignicons.com (third party)
* FontAwesome icons https://fontawesome.com/icons
* Maki icons (MapBox) https://labs.mapbox.com/maki-icons/editor/
* Simple Icons https://simpleicons.org
* Teeny icons https://teenyicons.com
* Tabler icons https://tabler-icons.io
* Open Iconic https://useiconic.com/open
* Evil icons https://evil-icons.io
* Remix icons https://remixicon.com
* Bytesize icons https://danklammer.com/articles/svg-stroke-ftw/#give-it-a-spin
* ...so many more :)

Related issue (GitHub markdown, poor contrast in dark mode): https://github.com/microsoft/fluentui-system-icons/issues/152 )

**Comment by danielweck** [comment]
By the way, this seems like a duplicated issue: https://github.com/microsoft/fluentui-system-icons/issues/31

**Comment by Jay-o-Way** [comment]
I always love to check https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font when I'm searching for an icon. Is that what you mean in this request, @prysmanta ?

**Comment by aatmmr** [comment]
Have a look at https://fluenticons.co/ which provides performance, search as well as a light and dark theme switch.

**Comment by danielweck** [comment]
https://fluenticons.co

Great job @fayazara :)

**Comment by fayazara** [comment]
Thanka @danielweck. Here's a v2 I have been working on the weekends. Will release it soon. 

https://fluenticons-next.vercel.app/

**Comment by tomi-msft** [comment]
[this is the official page](aka.ms/fluentui-system-icons)
