### ISSUE TITLE
the react icons are importing a 5 year old react-jsx package + babel-standalone

### ISSUE THREAD

**Issue by jeremy-coleman** [microsoft/fluentui-system-icons#197]
Look at the generated files
(Source when i opened this)
https://github.com/microsoft/fluentui-system-icons/blob/0f680d0786ad2f630b97c6db6f2a1d37df6b1192/packages/react-icons/src/components/AccessTime24Filled.tsx

As of march 7th, currently empty, idk.
https://github.com/microsoft/fluentui-system-icons/blob/master/packages/react-icons/src/components/AccessTime24Filled.tsx

they are importing this package for the JSX namespace for some reason. That package is also using new Function aka eval.
https://github.com/bigpipe/react-jsx/blob/master/index.js

https://bundlephobia.com/result?p=react-jsx@1.0.0
https://bundlephobia.com/result?p=jquery@3.5.1
889.4kb / 87.6kb = 10.15x
10 copies of jquery for 1 icon

**Comment by spencer-nelson** [comment]
This dependency will be removed with the esnext package handling. As an example you will see something that is built to be roughly like:
import * as React from "react";
const Accessibility16Filled = (iconProps, props) => {
    const { primaryFill, className } = iconProps;
    return React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", xmlns: "http://www.w3.org/2000/svg", className: className, "aria-label": props["aria-label"], "aria-hidden": props["aria-hidden"] },
        React.createElement("path", { d: "<snip/>", fill: primaryFill }));
};
export default Accessibility16Filled;

**Comment by jeremy-coleman** [comment]
Thats not a valid excuse lol
