### ISSUE TITLE
Question: Specify License/Redistribution terms for new Windows Segoe Fluent Icons

### ISSUE THREAD

**Issue by lukeblevins** [microsoft/fluentui-system-icons#202]
Windows Dev Channel builds include the new Segoe Fluent Icons font. Are developers allowed to include the TTF in their apps under the same MIT license to keep their experience consistent for users across Windows versions?
![image](https://user-images.githubusercontent.com/20365014/110230690-a9b64180-7ee0-11eb-882b-542586682af3.png)

**Comment by mdtauk** [comment]
I would have thought it would be included with WinUI as well as newer versions of Windows

**Comment by ismaelestalayo** [comment]
I'm very interested in this as well.
While I'm still far from publishing my update, I already integrated the new font in my app by bundling it as an asset, so different users in different Windows versions won't see different glyphs.

**Comment by riverar** [comment]
@lukeblevins I see you closed this last month, did you ever resolve this? Am curious about doing the same.
