### ISSUE TITLE
Strange results when using Fluent System Icons in Word

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/fluentui-system-icons#217]
Hi. Today Niels mentioned that Microsoft is again introducing new icons / a new font. I took a look in this repo and fount the TTF files. Installed them on my PC and fiddled around in Word (2010, in case that's relavant) using the Insert Symbol tool. The icons are shown in the tool window, but when inserted in the document, many icons are not drawn as they should be. Seems like it falls back to a couple of different fonts, like Times, Arial, SimSun...
![image](https://user-images.githubusercontent.com/65828559/112172459-0611a480-8bf5-11eb-8a29-87de59e78199.png)

Also, in the Insert Symbol tool, there are sub-sections (visible in the top-right corner) that are based on older, normal fonts. They are not useful in an icon font like this.
![image](https://user-images.githubusercontent.com/65828559/112172695-378a7000-8bf5-11eb-81aa-542b83168f40.png)

**Comment by Jay-o-Way** [comment]
A couple of actual Arabic letters are included in the font. Is there a reason or is this a mistake?
![image](https://user-images.githubusercontent.com/65828559/112176306-46beed00-8bf8-11eb-9745-6886b204c03c.png)

**Comment by Jay-o-Way** [comment]
Hello? Anybody out there?

**Comment by spencer-nelson** [comment]
Hello,

Apologies for the silence. The font here has very limited support and is currently only planned for use with Flutter projects.

That being said, when I installed it and just changed the font in my version of word it worked. I didn't try to add it as a symbol but as a 'normal' glyph by copying the codepoint from FontBook and pasting it in the document (TextBox in this screenshot).

![WordFluentIconFont](https://user-images.githubusercontent.com/53240053/114621156-3632ed00-9c61-11eb-808a-e649f7322ec1.png)

**Comment by Jay-o-Way** [comment]
> That being said, when I installed it and just changed the font family in my version of word it worked. I didn't try to add it as a symbol but as a 'normal' glyph by copying the codepoint from FontBook and pasting it in the document (TextBox in this screenshot).

Thanks for the respons. Some icons do work as they should - a few examples marked in green in my initial screenshot.
The cause of the problem is not clear to me though. Does anybody know? I'm **guessing** this font was created by changing an existing font step by step, rather than starting from scratch. I think starting from scratch would be a very smart thing to do though, since an icon font is so different from a text font.

To explain what I meant by "reverting to a different font" was that for some cases the icon is not shown. Then I select the char and check the the Font Selection box (in Word's ribbon) and there is a different font (Calibri, Times, Arial, SimSun, ....) and manually setting it to Fluent does not work.

**Comment by spencer-nelson** [comment]
The font is created in the [importer](https://github.com/microsoft/fluentui-system-icons/blob/master/importer/package.json) script, using [icon-font-generator](https://www.npmjs.com/package/icon-font-generator). If you would like to play with it to see how it all works you can run the script yourself. In particular note the `generate:font-regular` entry point as it is called from `build:fonts`. This will put fonts in an importer/dist folder that you can inspect. The font file itself is created fresh each run, but note that it takes codepoints from the fonts/FluentSystemIcons-xxx.json files.

I don't know the inner workings of the Word symbol picker, but I believe the 'reverting' you see is a common fall-back method used by rendering systems when a particular code point/glyph doesn't exist for the given font, where they fall back to the same code point in a system font.

**Comment by Jay-o-Way** [comment]
Honestly, I don't really need to work with this, so I don't need it to be perfect. For the same reason, I do not think I have the time or the will to investigate your suggestions (with all do respect) because that's all completely new to me. What I would like to see is that somebody recognizes the things I have mentioned - give a bit of explanation if possible - and (s)he knows how to fix/improve it.

**Comment by mdtauk** [comment]
The font does not use the same unicode values as a normal text font, and is designed for use with web-browsers and App UI frameworks which can display glyphs by their unicode index value.

Word is not optimised for this AFAIU

**Comment by Jay-o-Way** [comment]
So, is this still an issue?

**Comment by Jay-o-Way** [comment]
I guess this is not an issue?

**Comment by spencer-nelson** [comment]
The intended use of the fonts built by the pipelines here is primarily for developer use, where codepoints are directly referenced, rather than in a more integrated typographic system like the Word picker/canvas. I've forwarded the thread on to some folks that work more closely with the picker and Office typography, in case it aligns with any of their concerns, but will close the thread as something we don't plan to address.
