### ISSUE TITLE
Icons library

### ISSUE THREAD

**Issue by bennymeg** [microsoft/fluentui-system-icons#220]
First of all I most say, great job, I love the new Fluent UI icons.

I had a hard time browsing the massive amount of icons you designed, so I built a website so I could browse the quicker.
I most say it ended up quite nice and it updates automatically weekly (only a icon search bar / filter is missing).

Take a look: https://bennymeg.github.io/ngx-fluent-ui/ .
If you like, feel free link it along side the markdown document link.

Benny.

**Comment by Jay-o-Way** [comment]
Looks nice. Can you add the hexadecimal position numbers?

**Comment by bennymeg** [comment]
Tnx,
I'm not sure what are the icons hexadecimal position numbers and where they are used (I am using the svg file names) but if you can point me to them ill take a look.

**Comment by mdtauk** [comment]
> Looks nice. Can you add the hexadecimal position numbers?

I think you mean the Unicode glyph value, and this would be for the font that is outputted by the repo.

It would be good to be able to click on one of the icons, to view a popup showing all the sizes available for the icons

**Comment by Jay-o-Way** [comment]
> I think you mean the Unicode glyph value,

That's what I mean :-)

**Comment by mdtauk** [comment]
> > I think you mean the Unicode glyph value,
> 
> That's what I mean :-)

![image](https://user-images.githubusercontent.com/7389110/112634180-2bd7bd00-8e32-11eb-9c63-46ad6eeca68a.png)

**Comment by jsdpr1503** [comment]
hey can anyone provide all icon name with Unicode
i want to update it to my project

**Comment by mdtauk** [comment]
> hey can anyone provide all icon name with Unicode
> i want to update it to my project

https://github.com/microsoft/fluentui-system-icons/blob/master/fonts/FluentSystemIcons-Filled.json
https://github.com/microsoft/fluentui-system-icons/blob/master/fonts/FluentSystemIcons-Regular.json

**Comment by jsdpr1503** [comment]
thanks

**Comment by bennymeg** [comment]
> I think you mean the Unicode glyph value, and this would be for the font that is outputted by the repo.

Hmm, I didn't knew it was available as a font too, now it make sense.

> It would be good to be able to click on one of the icons, to view a popup showing all the sizes available for the icons

No problem, I will also add the import file name and the hex value as a pop up.

> https://github.com/microsoft/fluentui-system-icons/blob/master/fonts/FluentSystemIcons-Filled.json
> https://github.com/microsoft/fluentui-system-icons/blob/master/fonts/FluentSystemIcons-Regular.json

Thanks, that would be pretty easy now to add it to the icon library site.

**Comment by bennymeg** [comment]
Added hexadecimal position numbers & search box =]

**Comment by jsdpr1503** [comment]
Sir can I get an list of icons like

Icon(image or icon).      Icon name.       Unicode

**Comment by cervonwong** [comment]
Hi! This really saves a lot of time as I can search for icons much much faster. But I noticed that some of the newer icons such as 'Animal Cat' which was introduced 20 days ago and 'Drive Train' which was introduced on 3 April have not been added to the website.

Would it be convenient to update the website on each release of the icon set? Thanks

**Comment by bennymeg** [comment]
I am not planning to update it manually, I wrote a pipeline to update the website automatically every week.
Unfortunately, It has a bug and I haven't got the time to take a look at it yet, so that's the reason these icon are missing currently.

**Comment by cervonwong** [comment]
Thanks for the update. Your web app will certainly boost the convenience of using this icon set. 👍🏻

**Comment by tomi-msft** [comment]
[this is the official website](aka.ms/fluentui-system-icons)

**Comment by Jay-o-Way** [comment]
Just wanna say that WinUI 3 Gallery has basically the same thing :)
