### ISSUE TITLE
Gradle build error

### ISSUE THREAD

**Issue by tipapro** [microsoft/fluentui-system-icons#240]
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find :unspecified:.
     Required by:
         project :app > com.microsoft.design:fluent-system-icons:1.1.122
         

Maybe this is caused by '<artifactId>unspecified</artifactId>' line?

**Comment by MichaelC11** [comment]
Hi there! I hit this issue too :(

Note: I did notice that an earlier version (e.g., 1.1.112) doesn't have this issue - so I wonder if it's a more recent regression?

**Comment by tipapro** [comment]
> Hi there! I hit this issue too :(
> 
> Note: I did notice that an earlier version (e.g., 1.1.112) doesn't have this issue - so I wonder if it's a more recent regression?

I solve it with:
    implementation ("com.microsoft.design:fluent-system-icons:1.1.122") {
        exclude module: 'unspecified'
    }

**Comment by MichaelC11** [comment]
Neat, thanks!! :)

**Comment by yunu7067** [comment]
> > Hi there! I hit this issue too :(
> > Note: I did notice that an earlier version (e.g., 1.1.112) doesn't have this issue - so I wonder if it's a more recent regression?
> 
> I solved it with:
> implementation ("com.microsoft.design:fluent-system-icons:1.1.122") {
> exclude module: 'unspecified'
> }

It works! Tnx!!

**Comment by Adamantcheese** [comment]
This has been occurring since 117; 116 is the last version that doesn't have this issue. Seems to be related to the move to Maven Central from JCenter in regards to that repository's deprecation.

**Comment by willhou** [comment]
@tipapro @MichaelC11 @yunu7067 @Adamantcheese 

Sorry about that. Can you try adding `@aar` to the end of the dependency? This should explicitly request for the aar hosted on maven central instead of a jar(by default).
```groovy
implementation 'com.microsoft.design:fluent-system-icons:1.1.127@aar'
```
