### ISSUE TITLE
what's the rule behind at 1.5px stroke?

### ISSUE THREAD

**Issue by UIenhancement** [microsoft/fluentui-system-icons#241]
Icons are design at  24 PX  (Regular- 1,5px stroke)
12, 16, 20pixel --> 1
24, 28  pixel --> 1,5px   
48 pixel--> 2,5 px

Haw this rule reflect with filled? 

thank you for the clarification ;)

**Comment by spencer-nelson** [comment]
Hi, you can see the guidelines for the stroke in https://www.figma.com/community/file/836835755999342788/Microsoft-Fluent-System-Icons in the Guidelines page, Creation-Strokes 1 artboard.

In short, for filled icons you add .5 to the stroke weight of what it would be for Regular.
