### ISSUE TITLE
Fluent design system guideline does not use Fluent UI System Icons

### ISSUE THREAD

**Issue by TaigaYamada** [microsoft/fluentui-system-icons#255]
On the Fluent design website, one can find guidelines for designing according to the Fluent design system on the Web and Windows.

The problem is, the guideline concerning neither web nor Windows seems to be using the Fluent UI System Icons.

- https://developer.microsoft.com/en-us/fluentui#/styles/web/icons
![image](https://user-images.githubusercontent.com/77144664/118906606-08744e80-b959-11eb-9b84-5ed40fa333f3.png)

- https://docs.microsoft.com/en-us/windows/uwp/design/style/icons
![image](https://user-images.githubusercontent.com/77144664/118906691-36f22980-b959-11eb-92b6-41abdace6afc.png)

Shouldn't the guideline for Fluent design system use Fluent UI System Icons?

**Comment by cervonwong** [comment]
I would also like to add that I can't find pages on the Fluent design website linking to this icon set

**Comment by mdtauk** [comment]
The Icon set is not currently the default in use, that will probably change with 21H2 and the "Sun Valley" refresh - and WinUI 2.6 is starting to use some of the new icons.

Build is in a few days, so you may see updated guidelines soon after.

**Comment by TaigaYamada** [comment]
Ah, I see.
I'll be on the lookout for Build. Thank you.

**Comment by jasoncuster** [comment]
Thanks gang - this is something we're addressing in guidance relatively soon, with a fully searchable solution coming later (unsure of timeline yet).

**Comment by TaigaYamada** [comment]
That is absolutely fantastic to hear! This is by far the best icon set, and it's receiving very active development on top of that. 

Thank you for everything so far, and I'm looking forward to the upcoming developments.

**Comment by TaigaYamada** [comment]
With Windows 11 now in general availability, shouldn't the icon guideline of the Fluent design system use the Fluent UI icons?

**Comment by tomi-msft** [comment]
[This is the website to find the new Fluent Icons](https://aka.ms/fluentui-system-icons)
