### ISSUE TITLE
Request: zoom in/out icons

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/fluentui-system-icons#268]
I tried to search a bit but I couldn't find any icon to represent zoom in and out.
I would imagine this icons to be represented by a magnifying glass with a +/-.

**Comment by FrayxRulez** [comment]
I guess this is done... :)

**Comment by jasoncuster** [comment]
Sorry about that @FrayxRulez - we added those a while ago. Apologies - I'm not great at keeping up with these issues...haha. Thanks for contributing!

**Comment by FrayxRulez** [comment]
No problem 😂 I made my own in the wait and I now replaced them with the official ones! Keep up the hard work
