### ISSUE TITLE
React icons wrap svg on span making it change size according to line-height

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui-system-icons#276]
Hi there!

I'm trying to migrate my product to these icons following https://hackmd.io/RPZl3VIDRz-sobbE48IJuQ ... while doing so I noticed that the SVG is always wrapped in a `<Span />` element, which ends up making the icon bigger than expected.

I noticed that in my case, the line height is set to 1.15, which makes the span height `24px`  even though the SVG itself is `20px` height. If that span had `line-height: 0` set (or `display: inline-flex` to make it ignore the line height), then the size of the SVG would be respected and there wouldn't be extra growth.

This extra whitespace makes it so that my icons end up misaligned whenever I align them using flex (e.g. `justify-content: center`).

**Comment by tomi-msft** [comment]
Hi @PatoBeltran , thanks for filing the issue! I can go ahead and add default styling to the span around the svgs that will set `display: inline-flex` and that should fix your issue!

**Comment by sjwilczynski** [comment]
Hi, I wanted to bump to version 1.1.134 but even then I don't see the default stiles for the icon. The `root-span` class seems to be empty:
![image](https://user-images.githubusercontent.com/19153565/124600883-7f14cf00-de67-11eb-9a6b-7b103daab35b.png)
![image](https://user-images.githubusercontent.com/19153565/124600900-8340ec80-de67-11eb-9835-98b06183defb.png)
@tomi-msft do you know what is causing the issue?

**Comment by tomi-msft** [comment]
This should be fixed now
