### ISSUE TITLE
Unassigned child when building against Xcode 13

### ISSUE THREAD

**Issue by levinli303** [microsoft/fluentui-system-icons#280]
one example is:
https://github.com/microsoft/fluentui-system-icons/blob/fcd1b4071d89819f8982602bda6a1bf87f896078/ios/FluentIcons/Assets/IconAssets.xcassets/ic_fluent_text_direction_horizontal_24_filled.imageset/Contents.json

two children shared the same properties: locale: en idiom: universal.

<img width="625" alt="Screen Shot 2021-06-15 at 6 50 31 PM" src="https://user-images.githubusercontent.com/17924287/122041008-1065c800-ce0b-11eb-8964-1e851ebab94f.png">

**Comment by nickromano** [comment]
Fixed in #286. Thanks!
