### ISSUE TITLE
TABLE OF ICONS

### ISSUE THREAD

**Issue by PedroGuilhermeFariaDuarte** [microsoft/fluentui-system-icons#291]
Hello everyone!!

Is possible create a table or site like  [react-icons](https://react-icons.github.io/react-icons/).

Is very hard search a icon in actual version, for example:

**Comment by YBAZAN** [comment]
Hi,

You can look at this url: https://bennymeg.github.io/ngx-fluent-ui/

See this issue for more information: https://github.com/microsoft/fluentui-system-icons/issues/220

**Comment by PedroGuilhermeFariaDuarte** [comment]
Thanks! 😃
