### ISSUE TITLE
Many Broken Icons in CSS Version

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/fluentui-system-icons#318]
Many of the icons referenced in the CSS file seem to be broken.  If you look at the FluentSystemIcons-Regular.html file it looks like this:

![image](https://user-images.githubusercontent.com/4465616/132137728-6961c07e-bc9c-4527-b318-fc33529a31d8.png)

**Comment by vnbaaij** [comment]
If you replace the content in css file that are 5 characters long and start with `\100` or `\200` with `\0` almost all of them are shown. As far as i can see there are only 4 bad ones left: 
`
.icon-ic_fluent_checkbox_checked_sync_20_regular:before {
    content: "\000";
}
.icon-ic_fluent_document_dismiss_16_regular:before {
    content: "\009";
}
.icon-ic_fluent_document_link_16_regular:before {
    content: "\00a";
}
.icon-ic_fluent_emoji_sad_16_regular:before {
    content: "\00d";
}
`
Not found what the codes for these are supposed to be

**Comment by scottkuhl** [comment]
That does fix a lot of them.  I also noticed that the alignment icons are the wrong ones.

![image](https://user-images.githubusercontent.com/4465616/132390803-5094b8d4-0dc8-4319-b854-7918dcfb1061.png)


![image](https://user-images.githubusercontent.com/4465616/132390694-52beab64-ae33-471d-af14-8a32a79b9c84.png)

**Comment by Phvli** [comment]
This issue still persist.

**Comment by scottkuhl** [comment]
With each release the problem continues to change.  Some icons are fixed and others are broken.  I don't know how this CSS file is being generated, but it is not working.  If you run the font file through a service like https://andreinitescu.github.io/IconFont2Code/ you will find issues.  This needs to be fixed.  It's been going on for months.

**Comment by spencer-nelson** [comment]
This should have been fixed with https://github.com/microsoft/fluentui-system-icons/pull/438 and it appears ok to me when I look at the current version of fonts/FluentSystemIcons-Regular.html. Please correct me if this is still appearing.
