### ISSUE TITLE
Can no longer view all icons - too many icons for github to show a size of that file

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fluentui-system-icons#326]
You can no longer see icons on this page: https://github.com/microsoft/fluentui-system-icons/blob/5d706f569c50697757247907505f3836fa480635/icons.md

![image](https://user-images.githubusercontent.com/2684369/135667122-faec83b7-3ff7-45c2-ba08-4a2300ab4b0a.png)

**Comment by JamesBurnside** [comment]
If there is somewhere else to view the list of icons update the homepsage readme: https://github.com/microsoft/fluentui-system-icons#icon-list

**Comment by spencer-nelson** [comment]
Please see [issue 324](https://github.com/microsoft/fluentui-system-icons/issues/324)
