### ISSUE TITLE
"Address book" versus "Address book number"

### ISSUE THREAD

**Issue by patrickhlauke** [microsoft/fluentui-system-icons#33]
Maybe a mistake, but...not quite getting what the difference between these two is supposed to be (as the former also has the "#" symbol).

> ![screenshot showing the two icons which look mostly identical](https://user-images.githubusercontent.com/895831/85674208-92ba2100-b6bc-11ea-9491-f02565f71c25.png)

**Comment by spencer-nelson** [comment]
Thanks for bringing this to our attention. The name of the pictograph has been updated to just "Book Number" and it has been tagged in the Figma file with the Address Book metaphor.
