### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by fareezMaple** [microsoft/fluentui-system-icons#34]
How can i integrate with existing flutter project?

**Comment by polilluminato** [comment]
Just an idea but maybe we can use [FlutterIcon](https://www.fluttericon.com/) to create fonts to be used with Flutter. I try to follow this two guides and it works:
- [How to use custom icons in Flutter](https://medium.com/flutterpub/how-to-use-custom-icons-in-flutter-834a079d977)
- [Flutter Custom Icons – Automatic & Manual Way (Icon Font or SVG)](https://resocoder.com/2019/08/15/flutter-custom-icons-automatic-manual-way-icon-font-or-svg/)

It creates a class that can be imported in a Flutter project, the class exposes fonts as IconData so we can use it with the Icon Widget.

**Comment by polilluminato** [comment]
I made a little repo to showcase what I'm talking about, you can check here: [flutter-fluentui-icons-sample](https://github.com/polilluminato/flutter-fluentui-icons-sample).

It's a little app where I downloaded some icons, created the ttf font file with [FlutterIcon](https://www.fluttericon.com/) and imported it.

Maybe if you find it useful I/we can create a Flutter Package and share it on [pub.dev](https://pub.dev/). 
I don't know very much about licensing but I can write to opencode@microsoft.com and ask about it.

**Comment by willhou** [comment]
Thanks for sharing all the info, that's something we are looking into as well, we will definitely take what you have shared into considerations 👍

**Comment by fareezMaple** [comment]
Thank you @polilluminato . It works great!

**Comment by polilluminato** [comment]
Thanks @fareezMaple.

@willhou I made a Flutter package, and published it on pub.dev: [fluentui_icons](https://pub.dev/packages/fluentui_icons).

By now it's in 0.1.0 version, I added all the Fluent UI Icons and it's still in active development because I'm looking for automate some stuff that I have to do to get all the SVG in the right directory to create the .ttf font with [FlutterIcon](https://www.fluttericon.com/).

**Comment by willhou** [comment]
Thanks @polilluminato for the interest again. We will have Flutter support in the coming up releases and in the mean time, please feel free to do what you need that suits your use case!

**Comment by aakash1313** [comment]
@fareezMaple , We have now added the flutter support for the fluent icons library and it is published on the pub.dev. Feel free to use it and let us know if you find any issues . Thanks :) 

https://pub.dev/packages/fluentui_system_icons
