### ISSUE TITLE
Font file included in Windows 11 is outdated

### ISSUE THREAD

**Issue by TaigaYamada** [microsoft/fluentui-system-icons#346]
Hello.

Recently, I updated my computer to Windows 11.
I see that by default, "Segoe Fluent Icons" font is installed in Windows 11. However, the version listed is 1.00, and there are many missing icons in this font compared to the "FluentSystemIcons-Regular" font, version 1.1.147, available in this github repository.

Are there any plans to update the icon font included in Windows 11?

**Comment by spencer-nelson** [comment]
Thanks for your interest.

Segoe Fluent contains a subset of the larger Fluent icon collection. It is intended for Windows 11 controls and various common commands. While we would love to include more of the collection for our 3rd party partners, we need to balance that desire with certain performance, file size, and update frequency restrictions. Segoe Fluent Icons is a rejuvenation of Segoe MDL2 icon font + additional icons required for Windows 11.
