### ISSUE TITLE
Icon Submission: Print 32px 

### ISSUE THREAD

**Issue by danielsoliman** [microsoft/fluentui-system-icons#357]
https://www.figma.com/file/TEwfepwOupa9HTtIWIPC0K/Icon-Submission%3A-Print-32-px?node-id=0%3A1

**Comment by jasoncuster** [comment]
Thanks @danielsoliman - there were a few update based on the adjusted grid and layout for 32px icons, but we've added it for the sprint merge this Friday. Thanks again!

<img width="419" alt="image" src="https://user-images.githubusercontent.com/20647412/161676548-702f67fd-8bc5-42bd-8c58-fd3d02b48b99.png">
