### ISSUE TITLE
Icon documentation no longer working because it is too large

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui-system-icons#359]
https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md

Currently displays:

![image](https://user-images.githubusercontent.com/20744592/142010836-7eea0701-e260-419e-b3b0-943c87c64bcf.png)

**Comment by ItzLevvie** [comment]
Duplicate of https://github.com/microsoft/fluentui-system-icons/issues/324.
