### ISSUE TITLE
Community icons website 

### ISSUE THREAD

**Issue by thipokch** [microsoft/fluentui-system-icons#36]
Thanks for sharing the icons! ❤️ I loved the shift from sharp Fabric icons to something more friendly and refined in Fluent.

I got so excited about the icons that I've mocked up a community-led icons website.
**I wonder if the team is working on the website though**? 

Otherwise, I'd love to jump in and develop the website. I'm also open to suggestions.

![FluentIconMockup](https://user-images.githubusercontent.com/20105675/85784696-64007280-b6dd-11ea-97ab-bf9b96ffb7de.png)

**Comment by willhou** [comment]
Thanks for the interest! For now if you are looking to search for an icon on a web browser, you can try doing so in the [icons.md](https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md) readme file. A website for showcasing the icons like our [Android and Mac demo apps](https://github.com/microsoft/fluentui-system-icons#demo-apps) is something we are considering but don't have more to share currently.

Please follow #31 for website updates.

**Comment by mubeenpatel99** [comment]
I am also in if developing the web interface is the thing you have in mind for future, contact me
