### ISSUE TITLE
Is it a good idea to import 34 Mb of images as a framework to the mobile app? 

### ISSUE THREAD

**Issue by wzbozon** [microsoft/fluentui-system-icons#37]
Subject

I don't think so. It is much better to import only those images, that you need.

**Comment by spencer-nelson** [comment]
We understand the concern for bloating your app with unused resources. If you are consuming the mobile libraries in your projects, consider enabling shrink resources for Android and running the exclusion script for iOS, as they will help preventing unused icons being bundled into the app.
The benefit of going that route is you can easily adapt and update to changes in the assets or a need to start consuming new ones. However, if you need to be absolutely minimal in what you grab, please feel encouraged to hand pick the images you need.
