### ISSUE TITLE
Icon Submission: Alert Badge

### ISSUE THREAD

**Issue by samhenrigold** [microsoft/fluentui-system-icons#371]
Hey there, I've been using this custom icon for a while and have been meaning to submit it, let me know if you'd need any changes made to push this to main. Thank you! 

[https://www.figma.com/file/Jm6i3O4gfD433kyASLeb2E/Fluent-Alert-Badge](https://www.figma.com/file/Jm6i3O4gfD433kyASLeb2E/Fluent-Alert-Badge)

<img width="461" alt="Screen Shot 2021-11-30 at 2 03 31 PM" src="https://user-images.githubusercontent.com/49251320/144111115-82783e41-6e72-4d81-b6fa-04c59a25258b.png">

**Comment by samhenrigold** [comment]
Hey folx, any update on getting this icon added?

**Comment by jasoncuster** [comment]
Apologies @samhenrigold - time just keeps moving on. We're adding the icon Alert Badge to this merge on Friday.

**Comment by samhenrigold** [comment]
Amazing, thank you so much!
