### ISSUE TITLE
Different fill color in one icon

### ISSUE THREAD

**Issue by TheOnlyBeardedBeast** [microsoft/fluentui-system-icons#38]
First I would like to thank everybody who worked on these assets.

Yesterday I have built a React package for these icons and I found out that the icon `assets/Document Autosave/SVG/ic_fluent_document_autosave_24_filled.svg` has a different fill color than the other icons. It uses #292929 the others use #212121

**Comment by spencer-nelson** [comment]
Thanks for letting us know. This should get updated later today.
