### ISSUE TITLE
Build failed in Edge iOS.

### ISSUE THREAD

**Issue by xxycode** [microsoft/fluentui-system-icons#385]
I am from Edge iOS team, and trying to update fluent icon to latest version, but when i did it, i always got an error. I found there ara some mistakes in BUILD.gn
From line 35115 to 35141, the imageset name was wrong.
For example:
in line 35115
`imageset("ic_fluent_ios_arrow_ltr_24_filled") {
  sources = [
    "FluentIcons/Assets/IconAssets.xcassets/ic_fluent_ios_arrow_ltr_24_filled.imageset/Contents.json",
    "FluentIcons/Assets/IconAssets.xcassets/ic_fluent_ios_arrow_ltr_24_filled.imageset/ic_fluent_ios_arrow_ltr_24_filled.svg",
  ]
}`
in fact the folder under "FluentIcons/Assets/IconAssets.xcassets/" is "ic_fluent_ios_arrow_24_filled.imageset".
These will case build failed in Edge iOS.

**Comment by spencer-nelson** [comment]
This should be closed with #386 If not, please re-open it and I will offer profuse apologies.
