### ISSUE TITLE
Some icons appear disproportionately thick in filled version

### ISSUE THREAD

**Issue by TaigaYamada** [microsoft/fluentui-system-icons#403]
As per figma guideline Icon creation-Filled weight 1,

> The call end filled icon is slightly smaller than the filled state to help balance the icon and to keep the feeling the shape is supposed to have.

However, some icons in the filled variant appears considerably thicker compared to the regular icon.

ex. Accessibility
![image](https://user-images.githubusercontent.com/77144664/152675692-300fb2f1-2fe7-43c6-b22c-5d55bc5813ae.png)
![image](https://user-images.githubusercontent.com/77144664/152675698-18c41f27-42da-4a98-a939-00208b09560a.png)

ex. Airplane Take Off
![image](https://user-images.githubusercontent.com/77144664/152675719-7951205b-1f40-45d6-968a-f6d8895762fc.png)
![image](https://user-images.githubusercontent.com/77144664/152675726-39514bd3-7d3b-4dad-ae4e-79592727f268.png)

There may be other icons exhibiting the same property.

**Comment by jasoncuster** [comment]
It's a great point @TaigaYamada

What we have found is that some teams have used filled icons for hovers states, something that wasn't fully intended, but really it makes sense. Which means if you have a filled icon that is inconsistent in sizing - they dance a bit - something that is really obvious with hovering.

So as a rule now we default to the filled state being a true 1:1 shape as much as we can, with obvious differences being able to still have some shifting, but doing so minimally as much as we can. I hope this helps explain it - it's something we want to update in the guidance as we look to update that soon.
