### ISSUE TITLE
All Fluent 16x16 Icons On Iconify Are Not Correctly Centred

### ISSUE THREAD

**Issue by alexdobson** [microsoft/fluentui-system-icons#406]
It appears that all 16x16 fluent icons on Iconify [(here)](https://icon-sets.iconify.design/fluent/) have been sized and offset incorrectly - they are no longer centered like all other icons, and are also contained with 20x20 bounding box.

Here's an example of one 16x16 icon: 

<img width="182" alt="Screenshot 2022-02-15 at 16 12 34" src="https://user-images.githubusercontent.com/67032270/154102503-e512b92c-670d-4898-99f7-b468eadfbde4.png">

Notice how the icon is contained within a 20x20 box, instead of a 16x16 one, and is also off-centre.

**Comment by jasoncuster** [comment]
Haha, we have nothing to do with them being pulled into Iconify. Maybe there's a way to contact the devs that pull those in?
