### ISSUE TITLE
Need Fluent Icon replacements for ones that were deleted during the last rename - Rotate 'x' named icons

### ISSUE THREAD

**Issue by amoggo** [microsoft/fluentui-system-icons#407]
**User Impact:**
with the new Fluent Icon renaming, a bunch of icons that we were importing into devmain were deleted. This will affect the final product that's consuming these icons which are no longer imported as part of Nuget. So the expected fix is that the fluent icon team provides us with the correct icon replacements.

**Full Context:**

We have a nuget pipeline failure in our fluent icon repo and
It looks like it's due to a recent icon deletion/renaming that got rid of "ic_fluent_text_align_right_rotate_270_24_filled"

I tracked the repo commits and stumbled across this commit https://github.com/microsoft/fluentui-system-icons/commit/29de856f13add36dc938cb3c60489296e80b4408 which says `Text Align - Remove the 'Rotate x' for vertical and horizontal (as they are more clearly descriptive)` and I imagine this icon was removed.

There's currently no replacement icons for these. In essence, there is nothing in the file that visually matches the old icon. If you go to [https://www.figma.com/file/43oQOCD2164ExeSf5ajmou/?node-id=2708%3A10653](https://www.figma.com/file/43oQOCD2164ExeSf5ajmou/?node-id=2708:10653) and then to Text Align you can see the options currently there

List of affected icons are:

"ic_fluent_arrow_rotate_clockwise_24_regular",
"ic_fluent_rotate_left_24_regular",
"ic_fluent_rotate_right_24_regular",
"ic_fluent_text_align_center_rotate_270_24_filled",
"ic_fluent_text_align_center_rotate_270_24_regular",
"ic_fluent_text_align_justify_low_rotate_90_24_filled",
"ic_fluent_text_align_justify_low_rotate_90_24_regular",
"ic_fluent_text_align_justify_rotate_90_24_filled",
"ic_fluent_text_align_justify_rotate_90_24_regular",
"ic_fluent_text_align_left_rotate_270_24_filled",
"ic_fluent_text_align_left_rotate_270_24_regular",
"ic_fluent_text_align_right_rotate_270_24_filled",
"ic_fluent_text_align_right_rotate_270_24_regular",
"ic_fluent_text_direction_rotate_270_24_regular",
"ic_fluent_text_direction_rotate_90_24_regular",
"ic_fluent_textbox_align_bottom_rotate_90_24_filled",
"ic_fluent_textbox_align_bottom_rotate_90_24_regular",
"ic_fluent_textbox_align_middle_rotate_90_24_filled",
"ic_fluent_textbox_align_middle_rotate_90_24_regular",
"ic_fluent_textbox_align_top_rotate_90_24_filled",
"ic_fluent_textbox_align_top_rotate_90_24_regular",

Temporarily these icons will manually be added back into the fluent repo.

Still awaiting a more permanent fix where the Fluent Icon team adds replacements.

FYI @spencer-nelson

**Comment by spencer-nelson** [comment]
Closing this as part of clean-up. It should be fixed by now; if you still see missing icons here, please let me know.
