### ISSUE TITLE
Size 24 keyline inner-stroked

### ISSUE THREAD

**Issue by ProCode-Software** [microsoft/fluentui-system-icons#409]
On the Grids & Keylines page, the size 24 circle keyline is inner-stroked instead of center-stroked, which causes the circle to be at size 20 instead of 18.5 pixels.
Circle keylines for other sizes are center stroked. This makes the keylines inconsistent.

Thank you.

**Comment by jasoncuster** [comment]
Good catch! Thank you for calling that out. It's been updated in the public kit.
