### ISSUE TITLE
Make a website for the new icons like the Fabric icons.

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui-system-icons#465]
https://github.com/microsoft/fluentui-system-icons/blob/master/icons_regular.md

This markdown can't be read in darkmode github viewing. Please just spin up a simple next.js website that lets you wordwheel through them. It would be great to also look up things by mdl2 name through a site like that.

**Comment by dzearing** [comment]
It looks like @tomi-msft has one in the works, here:

https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/concepts-developer-icons--page

I think it needs some love; we should put usage on its own page separate from the catalog. It deserves its own dedicated area on the public docs, so that it matches the aesthetic and fits into the big picture perfectly. I think that's the plan, but any improvement in the interim is welcome.

Maybe we could update the git repo website to that, or at least replace the markdown links with the catalog he has.

We also control the https://aka.ms/fabricicons shortlink, once we have a good place to land.

**Comment by tomi-msft** [comment]
The page was updated in this PR: https://github.com/microsoft/fluentui/pull/24284
