### ISSUE TITLE
missing distinct warning vs error icons

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui-system-icons#466]
The error icon looks like a warning icon. (It should be called WarningCircle. An error circle would have a small x in it, which is missing from the list.

My use case is that i have rows of jobs in a tool. They have icons which can represent their running states:

idle
running 
passed
passed with warnings
failed

I don't quite seem to have enough icons to represent.

![image](https://user-images.githubusercontent.com/1110944/174905799-cb2be711-b88d-4087-abb1-5116d6914bb1.png)

Almost! But i just need the error icon (the filled circle with X)

**Comment by spencer-nelson** [comment]
Circle with an X is currently [Dismiss Circle](https://github.com/microsoft/fluentui-system-icons/tree/master/assets/Dismiss%20Circle).
Warnings are usually typified in the system with a rounded triangle akin to [Warning](https://github.com/microsoft/fluentui-system-icons/tree/master/assets/Warning)

**Comment by dzearing** [comment]
ah ha, thanks @spencer-nelson, that was it!
