### ISSUE TITLE
Missing Calendar icons

### ISSUE THREAD

**Issue by TheJoeFin** [microsoft/fluentui-system-icons#48]
I build a calendar app on Windows and there are a couple of icons which I use in my app which are missing from this icon pack.

- Go To Today
![image](https://user-images.githubusercontent.com/7809853/87316684-b61e0200-c4eb-11ea-812b-1eed43987327.png)

- Calendar Reply
![image](https://user-images.githubusercontent.com/7809853/87316719-bddda680-c4eb-11ea-8420-56b43ef668fe.png)

**Comment by jasoncuster** [comment]
Hi @TheJoeFin - we have those being designed this week and should have them by EOW. I'll let you know if there's any issue in timing.
