### ISSUE TITLE
Icon Request: Phone Chat

### ISSUE THREAD

**Issue by danielsoliman** [microsoft/fluentui-system-icons#485]
Want to use to demonstrate a sms, mms, or rcs message.

https://www.figma.com/file/RoqOqvuDnQJstZfw99E0eS/Fluent-Icons-%2F-Phone-Chat?node-id=0%3A1

![Size=16, Theme=Regular@3x](https://user-images.githubusercontent.com/73758068/186668659-cd1349f8-6673-4047-a29f-93408316b16b.png)
![Size=16, Theme=Regular](https://user-images.githubusercontent.com/73758068/186668661-542999e4-4a19-4311-9b1a-0330da8dc9f4.svg)
![Size=16, Theme=Filled@3x](https://user-images.githubusercontent.com/73758068/186668662-808e9880-1b28-4458-afce-714f0ad932fc.png)
![Size=16, Theme=Filled](https://user-images.githubusercontent.com/73758068/186668663-1ef1b469-478c-4c98-91f7-204259dbe80f.svg)
![Size=20, Theme=Filled@3x](https://user-images.githubusercontent.com/73758068/186668664-e7c94713-b915-4a35-9ff5-35dfddf2e34c.png)
![Size=20, Theme=Filled](https://user-images.githubusercontent.com/73758068/186668665-0444fa80-7d10-45b0-a61e-1363ae3bfd70.svg)
![Size=20, Theme=Regular@3x](https://user-images.githubusercontent.com/73758068/186668666-6a5a34c7-06d0-4acf-95ac-74715dcf466e.png)
![Size=20, Theme=Regular](https://user-images.githubusercontent.com/73758068/186668667-fe353a1e-02e9-4990-808c-ba4398a9c2ae.svg)
![Size=24, Theme=Filled@3x](https://user-images.githubusercontent.com/73758068/186668668-6db5e372-2f3f-4357-8925-b2240d256e3f.png)
![Size=24, Theme=Filled](https://user-images.githubusercontent.com/73758068/186668669-89350598-9ce7-4b46-8d4d-cada460d37d3.svg)
![Size=24, Theme=Regular@3x](https://user-images.githubusercontent.com/73758068/186668671-89495f85-e5b3-4955-9d55-6d7c13ef508b.png)
![Size=24, Theme=Regular](https://user-images.githubusercontent.com/73758068/186668673-bac03521-dbdf-4461-9f69-ffa2b42023c3.svg)

**Comment by jasoncuster** [comment]
Thanks @danielsoliman - we've added these to the list for tomorrows merge!

**Comment by jasoncuster** [comment]
These have been added.
