### ISSUE TITLE
Bug - Icon creation tool - Circle (16 X 16 )

### ISSUE THREAD

**Issue by UIenhancement** [microsoft/fluentui-system-icons#500]
![image](https://user-images.githubusercontent.com/83458494/195565521-fbf2ea51-77ba-4323-a5aa-5c276e862b23.png)
Creation tools / V2.37.1 / Figma file 

the circle of the appear to be too little

**Comment by jasoncuster** [comment]
Thanks @UIenhancement - this has been updated in the Figma community file.
