### ISSUE TITLE
Filled prop type expected to be string

### ISSUE THREAD

**Issue by natle01** [microsoft/fluentui-system-icons#518]
Passing in a boolean value for the "filled" prop produces an error as it is expecting a string.
Although the "filled" prop takes a boolean value, once you render it in the DOM you get an error that it should be a string.

Using version: 2.0.178

**Typescipt:**
![image](https://user-images.githubusercontent.com/74999478/200432769-39b28239-40e5-4bf8-913d-952fcddcd56b.png)

**Console:**
![image](https://user-images.githubusercontent.com/74999478/200432399-05011dc7-eb41-48bd-8c2f-b7e2a25d92ed.png)

**Comment by tomi-msft** [comment]
Hi @natle01, thanks for filing the issue! It looks like this is due to the `filled` prop being passed incorrectly as an svg prop in the `bundleIcon` utility. #523 should fix the issue

**Comment by natle01** [comment]
Great, confirmed it's fixed. Thanks for the quick push
