### ISSUE TITLE
Icons not mirrored when FluentUI ThemeProvider rtl is true

### ISSUE THREAD

**Issue by mgamis-msft** [microsoft/fluentui-system-icons#557]
Hi,

I am using icons ChevronLeft20Regular, ChevronRight20Regular from package @fluentui/react-icons version 2.0.194 that is wrapped with a ThemeProvider from package @fluentui/react version 8.98.3. The icons are not mirrored when rtl is set to true. Our library uses react version in range >=16.8.0 <18.0.0.

**Comment by tomi-msft** [comment]
[This](https://github.com/microsoft/fluentui-system-icons/pull/625) PR should fix the issue:
