### ISSUE TITLE
TextColorRegularIcon provides Korean version in path data for the SVG Icon

### ISSUE THREAD

**Issue by TheLarkInn** [microsoft/fluentui-system-icons#567]
Hi team! We recently bumped our react-icons version to 2.0.198 and discovered that using `TextColorRegularIcon` actually generates the Korean version of the icon instead of the English version. Here is a screen shot as an example: 

![image](https://user-images.githubusercontent.com/3408176/230533391-b64b76e4-b995-4294-8271-67ebebd7b65c.png)

After investigating we discovered that the `path` data generated in `chunk-7.js` (where the icon is found) is actually providing the Korean version of the icon, despite saying it is the TextColorRegularIcon. 

```javascript
const TextColorRegularIcon = props => {
  const {
    fill: primaryFill = 'currentColor',
    className
  } = props;
  return React.createElement("svg", Object.assign({}, props, {
    width: "1em",
    height: "1em",
    viewBox: "0 0 20 20",
    xmlns: "http://www.w3.org/2000/svg",
    className: className
  }), React.createElement("path", {
    d: "M12.5 2c.28 0 .5.22.5.5v3h1.5a.5.5 0 0 1 0 1H13v3a.5.5 0 0 1-1 0v-7c0-.28.22-.5.5-.5Zm-7 1a.5.5 0 0 0 0 1H9c-.02.58-.1 1.14-.43 1.71-.43.73-1.31 1.55-3.26 2.33a.5.5 0 1 0 .38.92c2.05-.82 3.17-1.75 3.74-2.75.57-.98.57-1.94.57-2.68V3.5a.5.5 0 0 0-.5-.5h-4ZM3 13.5c0-.83.67-1.5 1.5-1.5h11c.83 0 1.5.67 1.5 1.5v3c0 .83-.67 1.5-1.5 1.5h-11A1.5 1.5 0 0 1 3 16.5v-3Zm1.5-.5a.5.5 0 0 0-.5.5v3c0 .28.22.5.5.5h11a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-11Z",
    fill: primaryFill
  }));
};
```

I also checked [latest on unpkg](https://unpkg.com/@fluentui/react-icons@2.0.199/lib/icons/chunk-7.js) to verify that this was still broken and it appears to be.

We were on a much earlier (2.0.162) version of this package so I'm not sure if I can be helpful in understanding where this was introduced.

**Comment by spencer-nelson** [comment]
Thanks. We'll submit a fix with the next push.

**Comment by jasoncuster** [comment]
This bug has been fixed! Thank you for calling it out.
