### ISSUE TITLE
Missing currency icon. 

### ISSUE THREAD

**Issue by sivaprakashsj** [microsoft/fluentui-system-icons#58]
Provide currency icon.

**Comment by jasoncuster** [comment]
Hey @sivaprakashsj - We have a currency icon at 16, 20, 24px. Is there a size that you're looking for specifically?

**Comment by sivaprakashsj** [comment]
It'll be better if it looks like cash or else you can create cash icon seperately. 

We're looking for more icons from ranging popular currency symbols and social media icons. 

BTW, we're using this lib for our app. Looking forward with your team.

**Comment by mdtauk** [comment]
Currency and Money are different concepts,

**Comment by sivaprakashsj** [comment]
Ya BYW if you provide, it'll be better. 😎

**Comment by jasoncuster** [comment]
@sivaprakashsj Hey dude, sorry, we didn't have time to include an updated cash icon for Friday's merge, so we'll include it in our push on the 14th.

As for more currency icons, we won't be adding specific ones at this time as they fall under type more than icons, and as a small team, we need to focus on bringing more of the main glyphs for products over.

**Comment by sivaprakashsj** [comment]
Sure dude. We're using the whole icons set in our app. Looking very good.😎

**Comment by jasoncuster** [comment]
Hiiiiii @sivaprakashsj - just wanted to confirm that the **Money** icon has been added to the repository (a few sprints ago, sorry for the delay). Thanks for requested it.
