### ISSUE TITLE
React SubtractFilled and SubtractRegular icons are missing svg paths in the definition

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui-system-icons#584]
React SubtractFilled and SubtractRegular icons have pnly empty array of svg paths in their react chunks, for example 

https://npmjs.com/package/@fluentui/react-icons/@fluentui/react-icons/lib/icons/chunk-3.js

<img width="682" alt="image" src="https://github.com/microsoft/fluentui-system-icons/assets/13742664/d6872310-600f-4809-9edb-725db1dd11c5">

**Comment by dgtllion** [comment]
Fixed in 2.0.203!
