### ISSUE TITLE
Icon request: No audio device

### ISSUE THREAD

**Issue by riverar** [microsoft/fluentui-system-icons#600]
`Segoe Fluent Icons`, Unicode code-point `0xEA85`, is depicted in the system tray below. It was my understanding Segoe Fluent Icons was a curated _subset_ of the icons in this repository, but the No Audio Device icon appears to be missing.

![image](https://github.com/microsoft/fluentui-system-icons/assets/475132/b2edd27c-78b5-4599-9a99-0b41b124fe72)

Is that something that can be backported into this repository?

**Comment by spencer-nelson** [comment]
Just for clarity, it is not a subset of this, as it has many more icons in it that in the Fluent System Icon set.

However, there are a pair of icons I'd point you to. There is a Speaker Mute icon at https://github.com/microsoft/fluentui-system-icons/tree/main/assets/Speaker%20Mute or Speaker Off at https://github.com/microsoft/fluentui-system-icons/tree/main/assets/Speaker%20Off

**Comment by riverar** [comment]
Ah. I was hoping to get the same glyph into this icon set, to avoid Segoe Fluent Icon licensing headaches, but it doesn't like that will happen. It's very unfortunate that there's a mismatch of OS icons and the icons in this repository.

Thanks for triaging this!
