### ISSUE TITLE
Icon Request: Notification Bell

### ISSUE THREAD

**Issue by elliot-huffman** [microsoft/fluentui-system-icons#649]
Currently, only the service bell exists, e.g. 'ServiceBell24Regular'.
I would like to request more variations of the bell or add another bell type to use to represent notifications or a notification center.

For an example, please see the Azure Portal's notification center icon (the bell):
![Screenshot of Azure's notification bell](https://github.com/microsoft/fluentui-system-icons/assets/5030490/98e0b20f-e673-4976-8c64-a9bc7d094d42)
Can you add an exclamation point to the bell to indicate something to check on and other symbols?

Examples of variations that might be used for reference is the series of 'home' icons that already exist in this project.

**Comment by Trix07** [comment]
There are a few notification icons that you might find interesting; they are all referred to as `Alert`. Unfortunately, there is no alert icon with an exclamation point, but maybe you could use either `AlertOn` or `AlertUrgent`?

**Comment by elliot-huffman** [comment]
Oh wow, these alert bells are perfect. I totally missed them. Case closed, thanks for the heads up :)
