### ISSUE TITLE
Feature request: custom SF Symbols 

### ISSUE THREAD

**Issue by zhuorantan** [microsoft/fluentui-system-icons#68]
Is it possible to import FluentUI icons to apps as custom SF Symbols? By using custom SF Symbols, Fluent UI icons can also enjoy the same benefits as builtin SF Symbols. It can provide icons in different weight and support optical alignment.

Here is the [documentation](https://developer.apple.com/documentation/uikit/uiimage/creating_custom_symbol_images_for_your_app) of how to create custom SF Symbols.

**Comment by mdtauk** [comment]
Fluent Icons are not tied to any one typeface, so it is not possible to align the stroke widths and sizes to typography.  They are designed to be cross platform, and so work with various different typefaces.

**Comment by spencer-nelson** [comment]
Hello, thank you for your suggestion but we are not currently planning to support all of the pictographs in such a way as would be a good fit with SF Symbols. For use in iOS we suggest you use the Cocoapods or Carthage libraries as per the README at https://github.com/microsoft/fluentui-system-icons/tree/master/ios
