### ISSUE TITLE
Font subsetting plugin bug

### ISSUE THREAD

**Issue by ColeStansbury** [microsoft/fluentui-system-icons#684]
There appears to be a number of icons which are not rendering correctly when using the webpack subsetting plugin.

With plugin:
<img width="698" alt="image" src="https://github.com/microsoft/fluentui-system-icons/assets/39272001/bb6a801f-cf2f-43ce-976d-9106fcabdcea">

Without plugin:
<img width="698" alt="image" src="https://github.com/microsoft/fluentui-system-icons/assets/39272001/06b59cec-8305-4e04-b8bf-7208b25dc4a9">

Examples include
LineHorizontal416Filled
LineHorizontal320Filled
MoreVertical16Filled
MoreHorizontal16Filled

... and others

**Comment by tomi-msft** [comment]
Hi @ColeStansbury. This occurs because the plugin is trying to maintain the styles present in the svg icons by using style injection into the styles prop of the font icons. This has been fixed in the most recent version.

**Comment by ColeStansbury** [comment]
Thanks! I don't see this problem in 2.0.242 anymore

the subset plugin remains volatile though - see #723
