### ISSUE TITLE
Plans for Figma updates?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/fluentui-system-icons#748]
The Figma containing the System Icons has not been updated since March, are there plans to update this periodically, if not with every Icon merge?

**Comment by mdtauk** [comment]
More Icons being merged today, and still no updates on the Figma...

**Comment by willchavez** [comment]
@mdtauk, you'll have all the icon goodness today.

**Comment by willchavez** [comment]
those are @jasoncuster's words, haha

**Comment by mdtauk** [comment]
So is this just overlooked, or is the Figma on a different release cadence?

**Comment by jasoncuster** [comment]
Hey hey Martin — apologies for the delay, there's been many factors that have pushed this out. [If you take a look though at the updated set](https://www.figma.com/community/file/836835755999342788/microsoft-fluent-system-iconography), you'll see one of the reasons is some new icons!
