### ISSUE TITLE
New file icon missing

### ISSUE THREAD

**Issue by alcomposer** [microsoft/fluentui-system-icons#83]
Hi, I have been looking for a "new document" icon.

There are many "document" icons, but no "new".

What would be the correct Fluent UI way to show new document in an icon?  A plus "+" ?

(New as in "new blank document" as opposed to "open document")

**Comment by jasoncuster** [comment]
@alcomposer - great minds think alike! We're actually working on adding that to the set for this sprint. We'll be adding them next week in the repo (week after for the Figma kit).

**Comment by jasoncuster** [comment]
Hey @alcomposer - sorry for the super lateness of this reply, but we have the Document Add in the library and repo now. Thanks for the suggestion!
